def preprocess_text(text):
    # Example of replacing specific sequences with desired pronunciation
    text = text.replace("XV", "X V")
    text = text.replace("BY", "B Y")
    text = text.replace("BY", "B Y")
    text = text.replace("AP", "A P")
    text = text.replace("KC4", "K C 4")
    text = text.replace("CO", "C O")
    text = text.replace("CT", "C T")
    text = text.replace("DU", "D U")
    text = text.replace("EA-EH", "E A to E H")
    text = text.replace("EK", "E K")
    text = text.replace("EX", "E X")
    text = text.replace("FO", "F O")
    text = text.replace("GD", "G D")
    text = text.replace("HA", "H A")
    text = text.replace("HI", "H I")
    text = text.replace("HR", "H R")
    text = text.replace("IS", "I S")
    text = text.replace("JA-JS", "J A to J S")
    text = text.replace("LA", "L A")
    text = text.replace("LU", "L U")
    text = text.replace("LY", "L Y")
    text = text.replace("OH", "O H")
    text = text.replace("OK", "O K")
    text = text.replace("OM", "O M")
    text = text.replace("ON", "O N")
    text = text.replace("OX", "O X")
    text = text.replace("OY", "O Y")
    text = text.replace("OX", "O X")
    text = text.replace("ST", "S T")
    text = text.replace("SU", "S U")
    text = text.replace("TA", "T A")
    text = text.replace("RA-RZ", "R A to R Z")
    text = text.replace("UJ-UM", "U J to U M")
    text = text.replace("UN-UQ", "U N to U Q")
    text = text.replace("UR-UZ", "U R to U Z")
    text = text.replace("EM-EO", "E M to E O")
    text = text.replace("VU", "V U")
    text = text.replace("XU", "X U")
    text = text.replace("YA", "Y A")
    text = text.replace("YI", "Y I")
    text = text.replace("YN", "Y N")
    text = text.replace("YO", "Y O")
    text = text.replace("YS", "Y S")
    text = text.replace("YU", "Y U")
    # Add more replacements as needed
    return text